  CREATE TABLE students (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL UNIQUE,
      roll_number VARCHAR(50) NOT NULL UNIQUE,
      created_at TIMESTAMP NOT NULL
  );