# Database Connection Configuration (Pointing to Docker container)
spring.datasource.url=jdbc:mysql://localhost:3306/student_registry_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway Configuration Lifecycle Management
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.fail-on-missing-locations=true

systemProp.docker.host=tcp://127.0.0.1:2375

# Apache Kafka Broker Discovery Target Address
spring.kafka.bootstrap-servers=localhost:9092

# Producer Serialization Engines (Key & Value mapping rules)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# JWT Secret for validating tokens from Notification Service
app.jwt.secret=${JWT_SECRET}

